* Bitte um kritische Prüfung und Verbesserung
Liebe Mitbürger, liebe wissenschaftlichen Kollegen,

Die Corona-Krise bestimmt derzeit maßgeblich unser Leben und unsere Überlegungen.
Extreme Vorsichtsmaßnahmen wurden und werden getroffen.
Täglich ändert sich der Wissensstand und der Stand unserer Überlegungen und Einschätzungen.
Die Ereignisse überstürzen sich und das erschwert sorgfältige randomisierte Studien, um Mortalität und geeignete medizinische Interventionen kontrolliert zu untersuchen.
Wir sind also bisher vor allem auf Beobachtungsdaten beschränkt, und es ist von höchster Wichtigkeit, diese Beobachtungen systematisch zu erfassen und richtig zu beurteilen.

Für Beobachtungsstudien kann die Kausalitätstheorie verwendet werden um kausale Effekte zu untersuchen, wenn bestimmte Bedingungen erfüllt sind.
Ich und meine Kollegen forschten in diesem Bereich und sind der Überzeugung, dass in der heutigen Situation kausale Inferenzstatistik helfen kann, entscheidende aber noch immer offenstehende Fragen für die Allgemeinheit, Politiker und Wissenschaftler zu klären.

Da die Zeit drängt, veröffentliche ich diesen Entwurf mit Vorschlägen zur Datenerhebung, -veröffentlichung und auswertung hier auf GitHub als "lebendes" Dokument.
Auf diese Weise ist es möglich, sehr schnell und öffentlich 
- gemeinsam diese Pläne zu diskutieren und auszuarbeiten
- Daten zusammenzustellen
- statistische Modelle zu veröffentlichen und zu begutachten.

Bitte:
- arbeiten Sie an dem Dokument mit, wenn Sie sich dazu in der Lage sehen.
- schlagen Sie Korrekturen vor, wenn Sie Fehler in den Überlegungen dieses Dokuments sehen.
- stellen Sie kritische Fragen, wenn Sie Überlegungen in dem Dokument nicht verstehen -- auch als Laie.
- veröffentlichen und teilen Sie den Link zu diesem Dokument (und seinem GitHub repository), um zu helfen, die offenen Fragen in der Corona-Krise mittels statistische Ursachenforschung zu klären und das Wissen um diese Möglichkeiten zu verbreiten.
