Liebe Mitbürger, liebe wissenschaftlichen Kollegen,

Die Corona-Krise bestimmt derzeit maßgeblich unser Leben und unsere Überlegungen.
Extreme Vorsichtsmaßnahmen wurden und werden getroffen.
Täglich ändert sich der Wissensstand und der Stand unserer Überlegungen und Einschätzungen.
Die Ereignisse überstürzen sich und das erschwert sorgfältige randomisierte Studien, um Mortalität und geeignete medizinische Interventionen kontrolliert zu untersuchen.
Wir sind also bisher vor allem auf Beobachtungsdaten beschränkt, und es ist von höchster Wichtigkeit, diese Beobachtungen systematisch zu erfassen und richtig zu beurteilen.

Die Kausalitätstheorie kann kausale Effekte auch bei Beobachtungsstudien untersuchen, wenn bestimmte Bedingungen erfüllt sind.
Beobachtungsstudien sind Datenerhebungen ohne experimentelle Kontrolle, beispielsweise in der gegenwärtigen Corona-Krise, und im Unterschied zu randomisierten Doppel-Blind-Versuchsreihen, wie sie beispielsweise für pharmazeutische Zulassungsverfahren benötigt werden.
Experimente sind der goldene Standard zur Untersuchung von Wirkungen und Nebenwirkungen. 
Doch leider sind sie nicht immer möglich, wie uns diese Pandemie sehr deutlich vor Augen führt.

Ich und meine Kollegen forschten in diesem Bereich und sind der Überzeugung, dass in der heutigen Situation kausale Inferenzstatistik helfen kann, entscheidende aber noch immer offenstehende Fragen für die Allgemeinheit, Politiker und Wissenschaftler zu klären.


** Bitte um kritische Prüfung, Verbesserung und Mitarbeit
Da die Zeit drängt, veröffentliche ich diesen Entwurf mit Vorschlägen zur Datenerhebung, -veröffentlichung und auswertung hier auf GitHub als "lebendes" Dokument.
Auf diese Weise ist es möglich, sehr schnell und öffentlich 
- gemeinsam diese Pläne zu diskutieren und auszuarbeiten
- Daten zusammenzustellen
- statistische Modelle zu veröffentlichen und zu begutachten.

Bitte:
# - Veröffentlichen und teilen Sie den Link zu diesem Dokument (und seinem GitHub repository), um zu helfen, die offenen Fragen in der Corona-Krise mittels statistische Ursachenforschung zu klären und das Wissen um diese Möglichkeiten zu verbreiten.
# - Schreiben Sie ein Unterstützungsschreiben für die Erhebung und Veröffentlichung der [[Daten][Benötigten Daten]].
# - Stellen Sie [[Daten][benötigten Daten]] zusammen.
- [[https://github.com/gkappler/CausalCovid-19/issues][Stellen Sie kritische Fragen zu den Argumenten und Überlegungen in diesem Dokument -- auch als Laie.]]
- Arbeiten Sie an dem Dokument mit, wenn Sie sich dazu in der Lage sehen (Fork rechts oben, bearbeiten und pull request).
- Schlagen Sie Korrekturen vor, wenn Sie Fehler in den Überlegungen dieses Dokuments sehen.
- Tragen Sie statistische Regressionsmodelle bei, die der Kausalschätzung zugrundegelegt werden können.


* Wie gefährlich ist Covid19? Welche Behandlungen wirken? 
Derzeit wird viel diskutiert, ob Menschen "an" oder "mit" Corona versterben.
Die Frage ist, ob Corona *ursächlich* war für das Versterben einer Person, und wie gefährlich Covid-19 im Vergleich zu beispielsweise Influenza ist.
Obwohl diese Frage alle getroffenen Maßnahmen betrifft, ist sie anhand der veröffentlichten Zahlen leider nicht zu beantworten.
Repräsentative Antikörpertests können diese Frage klären und auch Obduktionen tragen durch das Expertengutachten wertvolle Informationen bei.

Die Ärzte in den Intensivstationen müssen täglich Behandlungsentscheidungen treffen.
Kürzlich traten einige Ärzte in Europa und den USA an die Öffentlichkeit, und berichteten Ihre Erfahrungen mit dem Intubieren bei Covid-19 Erkrankten Patienten:
Sie äußerten sich sehr überrascht, dass selbst bei niedriger Sauerstoffsättigung von ca. 50% viele Ihrer Patienten ohne Intubation die Krankheit überstehen, jedoch die intubierten Patienten zumeist versterben
(https://www.nytimes.com/2020/04/14/nyregion/new-york-coronavirus.html, https://www.youtube.com/watch?v=bp5RMutCNoI).
Derlei Erfahrungen sind anekdotisch und haben sind noch nicht wissenschaftlich geprüft.
Dennoch ist es wichtig und richtig, dass Ärzte sich über derlei Erfahrungen anektotisch austauschen:
sie sollen effiziente Behandlungsmethoden finden um Patienten in Intensivstationen bestmöglich zu helfen und sie nicht in bester Absicht mit Behandlungen totzubehandeln, die zwar sonst am besten sind, aber vielleicht bei dieser neuen Erkrankung schädlich.
Ärzte lernen von den Beobachtungen während ihrer Arbeit und durch Austausch und - leider - durch Versuch, Irrtum und Erfolg.
Diese Erfahrungen werden randomisierte Studien zur Wirksamkeit der Intubationsbehandlung anregen.
Doch dieser Prozess braucht seine Zeit, und heute müssen Entscheidungen getroffen werden.
Heute gibt es diese wissenschaftlichen, randomisierte Studien zum Behandlungserfolg von Interventionen noch nicht.

Wie wichtig wäre es in dieser katastrophalen Situation, nicht nur Anekdoten zu teilen, sondern alle Informationen aus dem Krisengeschehen systematisch zu sammeln, und so verlässliche wissenschaftliche Einschätzungen der Situation zu erhalten?
Wie wichtig wäre es so wissenschaftlich wie möglich über Ursachen und Wirkungen zu forschen und zu sprechen,  auch wenn kontrollierte Experimente noch nicht vorliegen?
Dies ist nicht unmöglich!
Es gibt statistische Verfahren der kausalen Inferenzstatistik, um *ohne* randomisierte Studien zu schätzen, welche medizinischen Maßnahmen Heilung ursächlich begünstigen bzw. negativ beeinflussen:
Die Theorie kausaler Effekte von R. Steyer bzw. propensity score matching nach Rubin.
Vereinfacht gesagt systematisieren diese Verfahren die Analyse anekdotischer Erfahrungen und korrigieren mathematisch die Verzerrungen, welche bei nicht-randomisierten Beobachtungen unvermeidlich sind.
Diese Verfahren ermöglichen auf Basis hinreichender Daten 
1. die Wirksamkeit medizinischer Maßnahmen durch systematische Beobachtung und Erfassung zu bestimmen
3. eine dringend benötigte Schätzung der durchschnittliche Mortalität von Covid19 in der Gesamtbevölkerung zu berechnen,
4. das bedingte Risiko im Falle einer Infektion zu versterben verlässlich zu quantifizieren, für Personen eines bestimmten Alters, Geschlechts und auch für bestimmten Vorerkrankungen.
5. Die Folgen evidenzbasierter Pläne zur Herdenimmunisierung abzuschätzen, d.h. welche 60%-70% der Bevölkerung mit dem geringsten Risiko erkranken könnten, und wie groß das Risiko dieser Personengruppen wäre, an der Erkrankung zu versterben.
6. Diese geschätzten Folgen einer kontrollierten Herdenimmunisieren können dann Annahmen des Risikos von Impfnebenwirkungen gegenübergestellt werden.
Diese Fragen sind in der gegenwärtigen Situation von höchster Dringlichkeit, um Ärzte im Krankenhaus, besorgte Bürger sowie Politiker bei der Entscheidung von Maßnahmen zu beraten.
Mit epidemiologischen Modellrechnungen lassen sich leider diese kausalen Fragen grundsätzlich nicht beantworten.
Vielmehr werden dort informierte, jedoch letztlich hypothetische Annahmen verwendet um Modell-Vorhersagen zu Treffen.


Die Kausalitätstheorie wurde für Umstände wie die Corona-Pandemie entwickelt um kausale Effekte in Beobachtungsstudien zu schätzen, d.h. wenn es nicht möglich ist, eine Kontroll- und Experimentalgruppe zu bilden.
Zur Schätzung von kausalen Inferenz-Modellen wäre es erforderlich, in Krankenhäusern und Gesundheitsämtern vorliegende Daten auf der Ebene von Einzelfällen zu erheben und anonymisiert der Forschung zur Verfügung zu stellen.

Leider werden derzeit nur zusammengefasste Fallzahlen systematisch veröffentlicht, mit unterschiedlicher Aufschlüsselung nach Land, Geschlecht, und Alter.
Auf Basis dieser Fallzahlen, d.h. ohne Daten auf Ebene von Einzelfällen lassen sich jedoch obige drängendsten Fragen nicht beantworten.


Erstaunlich wenige Studien haben Daten auf der Ebene von Einzelfällen der Covid-19 Erkrankung ausgewertet:
- [[https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30243-7/fulltex][Verity, R., Okell, L. C., Dorigatti, I., Winskill, P., Whittaker, C., Imai, N., Cuomo-Dannenburg, G., Thompson, H., Walker, P. G. T., Fu, H., Dighe, A., Griffin, J. T., Baguelin, M., Bhatia, S., Boonyasiri, A., Cori, A., Cucunubá, Z., FitzJohn, R., Gaythorpe, K., … Ferguson, N. M. (2020). Estimates of the severity of coronavirus disease 2019: A model-based analysis. The Lancet Infectious Diseases, 0(0). https://doi.org/10.1016/S1473-3099(20)30243-7]]

  Verwendet Korrekturverfahren, wie sie in der Epidemiologie verbreitet sind (Ghani, A. C., Donnelly, C. A., Cox, D. R., Griffin, J. T., Fraser, C., Lam, T. H., Ho, L. M., Chan, W. S., Anderson, R. M., Hedley, A. J., & Leung, G. M. (2005). Methods for estimating the case fatality ratio for a novel, emerging infectious disease. American Journal of Epidemiology, 162(5), 479–486. https://doi.org/10.1093/aje/kwi230). 
- [[https://www.bmj.com/content/369/bmj.m1327][Mahase, E. (2020). Covid-19: Death rate is 0.66% and increases with age, study estimates. BMJ, 369. https://doi.org/10.1136/bmj.m1327]]

- Johns-Hopkins Universität, enthält Daten aus Hubei Province, China, sowie einige Fälle aus den USA
  - Analysen-Repository: https://github.com/HopkinsIDD/nCoV-Sandbox
- Richardson, S., Hirsch, J. S., Narasimhan, M., Crawford, J. M., McGinn, T., Davidson, K. W., Barnaby, D. P., Becker, L. B., Chelico, J. D., Cohen, S. L., Cookingham, J., Coppa, K., Diefenbach, M. A., Dominello, A. J., Duer-Hefele, J., Falzon, L., Gitlin, J., Hajizadeh, N., Harvin, T. G., … Zanos, T. P. (2020). Presenting Characteristics, Comorbidities, and Outcomes Among 5700 Patients Hospitalized With COVID-19 in the New York City Area. JAMA. https://doi.org/10.1001/jama.2020.6775
- Sun, K., Chen, J., & Viboud, C. (2020). Early epidemiological analysis of the coronavirus disease 2019 outbreak based on crowdsourced data: A population-level observational study. The Lancet Digital Health, 2(4), e201–e208. https://doi.org/10.1016/S2589-7500(20)30026-1
- *Wenn Ihnen weitere Studien bekannt sind, fügen Sie diese bitte ein oder melden Sie diese als Kommentar in [[https://github.com/gkappler/CausalCovid-19/issues/1][Issue #1]].*
Diese Studien verwenden Daten, welche mühsam von den Forschern aus den Sozialen Medien und oft ungenannten Quellen zusammengestellt wurden.
Die meines Wissend umfangreichste Datensammlung der Johns-Hopkins Universität stellt zusammengeführte Daten als [[https://docs.google.com/spreadsheets/d/1jS24DjSPVWa4iuxuD4OAXrE3QeI8c9BC1hSlqr-NMiU/edit#gid=1841943470][google Tabelle]] zur Verfügung. Die darin enthaltenen Datenspalten sind in der [[Case-Data Exploration.ipynb][Daten-Exploration]] aufgelistet.


Daten auf Ebene von Einzelfällen sind erforderlich zur bestmöglichen Erforschung der Gefährlichkeit der Erkrankung und der Wirksamkeit von medizinischen Maßnahmen.
Sie fehlen aber, bzw. werden für einzelne Studien jeweils aus den Krankenhausdaten zusammengestellt, und nicht geteilt.

Wir regen an, die zentrale Sammlung und anonymisierte Veröffentlichung dieser Daten zu veranlassen.
Offensichtlich sind diese Gesundheitsdaten rechtlich besonders geschützt.
Unsere westliche Demokratien sind bereit, die Notwendigkeit von Chinas autoritären Maßnahmen der Ausgangssperre und Ortsdatenüberwachung zur Eindämmung der Erkrankung zu erwägen und zu adaptieren.
Westliche Demokratien sollten diskutieren, ob es nicht ein geringerer Eingriff in das soziale Gefüge freier Gesellschaften wäre, zuerst den Schutz persönlicher Daten für Erkrankte und Verstorbene im Seuchenfall einzuschränken.
Es ist an den Studien auf Basis von Einzelfalldaten deutlich abzulesen, dass diese Aufhebung des Schutzes von Krankheitsdaten Wissenschaftlern ermöglicht, wertvolle und praktische Erkenntnisse über die Covid-19 Erkrankheit zu erforschen.


Während für die Erforschung der durch den Virus verursachten Erkrankung Covid-19 augenfällig offene Daten aus offizieller Quelle fehlen, ist bei der Erforschung des SARS-Cov2 Genoms eine vorbildlich offene Forschungssituation zu beobachten:
die nötigen Daten für die wissenschaftliche Gemeinschaft sind offen verfügbar und ermöglichen eine nie dagewesene Beschleunigung der Erforschung (siehe European Commission https://horizon-magazine.eu/article/covid-19-how-unprecedented-data-sharing-has-led-faster-ever-outbreak-research.html).

Zumindest die freiwillige Freigabe der Daten durch Patienteneinverständnis sollte eingeholt werden, und eine entsprechende offizielle Dateninfrastruktur des Europäischen Center of Desease Control vorbereitet werden.
Für bereits verstorbene Patienten sind wir der Überzeugung, dass eine Rechtsgüterabwägung die Nutzung dieser anonymisierten Daten ebenso oder leichter zulässt als die Erfassung von Bewegungsdaten der Bevölkerung.
Wir wollen eine öffentliche Diskussion über den Umgang mit Daten zur Wissenschaftlichen Untersuchung in dieser Corona-Krise anregen.

Katastrophen sind plötzlich und unübersichtlich.
Um in zukünftigen Katastrophen angemessen reagieren zu können, scheint es uns ganz besonders wichtig, aus dieser Katastrophe zu lernen, wie schneller ein gutes Bild der Lage erlangt werden kann.
Daher regen wir an, die Veröffentlichung anonymisierter Daten zu den Verstorbenen bei zukünftigen Pandemien als gesetzlichen Automatismus im Seuchenschutzgesetz zu verankern.
Nur auf diese Weise ist gewährleistet, dass die internationale Forschergemeinschaft mit im Seuchenfall gebotener Geschwindigkeit und Aktualität die Gefährlichkeit der Erkrankung erforschen und evidenzbasierte Hinweise für praktische Ärzte geben kann, welche der getroffenen medizinischen Maßnahmen wirken und zu warnen, welche Maßnahmen schaden.

** Übersterblichkeit, Kausalitätstheorie und Zufallsexperiment
Die Kausalitätstheorie nach Rolf Steyer beginnt mit einer formalen Begriffsklärung durch das Zufallsexperiment.
Zur verständlichen Beschreibung der Theorie in Bezug auf Corona die reduzierteste Fassung ohne Berücksichtigung der Zeitpunkte oder des Krankheitsverlaufs:
- Zur Testung wird eine Person /U=u/ aus der Population ausgewählt (nicht randomisiert, sondern gemäß Testprotokoll).
- Das Testergebnis der Person wird erhoben, /X=x/. 
- Kovariaten werden erhoben /Z=z/ (Alter, Geschlecht und Vorerkrankungen etc..)
- Erkrankt die Person (/S=1/) oder bleibt sie asymptomatisch (/S=0/)
- Verstirbt (/Y=0/) oder heilt (/Y=1/) die Person?

Wahrscheinlichkeitstheoretisch sind dies Zufallsvariablen
- /U : \Omega \rightarrow/ Population
- /X : \Omega \rightarrow {0,1}/
- /Z : \Omega \rightarrow Z_{1} \times...\times Z_{n}/
- /S : \Omega \rightarrow {0,1}/
- /Y : \Omega \rightarrow {0,1}/

*** Teststichprobe und Population, Infektion und Test
Die Testung und die Auswahl der Stichprobe gewährleistet keine direkte Einschätzung, wieviele Personen in der Bevölkerung wirklich infiziert sind. 

Dazu müssten im obigen Zufallsexperiment die Verteilung der Probanden /U/ durch eine randomisierte/repräsentative Auswahl /U/' ersetzt werden.
- Eine Person /U'=u/ wird gleichverteilt aus der Population ausgewählt (randomisiert, wird aus test-ökonomischen Gründen nicht/kaum duchgeführt).
Die Erkrankung an Covid-19, /X'/, kann nur indirekt durch Tests erhoben werden.
Tests sind niemals absolut zuverlässig sondern durch Sensititivtät und Spezifizität gekennzeichnet, in bedingten Wahrscheinlichkeiten ausgedrückt[fn::https://www.centerforhealthsecurity.org/resources/COVID-19/serology/Serology-based-tests-for-COVID-19.html]:
- Sensitivität: /1-P(X'=1 | X=0)/
- Spezifizität: /1-P(X'=0 | X=1)/


*** Was ist die Übersterblichkeit durch Corona in der erhobenen Stichprobe?
Die Anteile (Wahrscheinlichkeiten) der versterbenden Personen in der Testpopulation sind 
- wenn test-negativ: /P(Y=0 | X=0)/,
- wenn test-positiv: /P(Y=0 | X=1)/.

Der durchschnittliche kausale Effekt einer Covid-19 Erkrankung auf die Sterblichkeit innerhalb der getesteten Stichprobe entspricht der Differenz dieser Wahrscheinlichkeiten /P(Y=0 | X=1)-P(Y=0 | X=0)/ und kann als durch *Covid-19 bedingte Übersterblichkeit innerhalb der Stichprobe* interpretiert werden.
Hier stellen sich grundsätzliche Probleme:
- Die Stichprobe ist nicht repräsentativ für die Gesamtbevölkerung.
- Die Wahrscheinlichkeit mit negativem Test zu versterben ist anhand der erfassten Testdaten nicht möglich.
  Diese Wahrscheinlichkeit könnte jedoch auf Basis veröffentlichter Sterberaten der Vorjahre abgeschätzt werden.
- Die Zufallsvariablen der Genesung /Y/ kann erst nach dem Ende der Erkrankung erhoben werden. 

Für Personen, die durch Geschlecht, Alter und Vorerkrankungen /Z=z/ charakterisiert sind, und 
- positiv auf Covid19 getestet wurden, ist das bedingte Sterberisiko /P(Y=0 | Z=z,X=1)/,
- negativ auf Covid19 getestet wurden, ist das bedingte Sterberisiko /P(Y=0 | Z=z,X=0)/,
Der /Z/-bedingte durchschnittliche kausale Effekt von Covid19 auf die Sterberate ist definiert als die Differenz dieser bedingten Wahrscheinlichkeiten: /ACE_{Z=z}(Y | X) = P(Y=0 | Z=z,X=1) - P(Y=0 | Z=z,X=0)/.
Dieser bedingte durchschnittliche Effekt /ACE_{Z=z}(Y | X)/ is spezifisch für Personen, die durch Kovariaten /Z=z/ (Alter, Vorerkrankungen, etc.) charakterisiert sind, und für diese Gruppe definiert als der Mehr-Anteil der versterbenden Personen, die Covid-19 positiv getestet wurden, über die zu erwartende Sterblichkeitsrate von Covid-19 negativ getesteten Personen hinaus.
*Es handelt sich also um die Covid-19 bedingte Übersterblichkeit von Personen mit Kovariaten Z=z.* 

*** Verallgmeinerung auf die Bevölkerung
**** Kausale Erwartungstreue 
Definitionen
1. Der (/Z=z/) *-bedingte kausal erwartungstreue Erwartungswert* von /Y/ gegeben /X=x/ ist definiert als

   CUE_{Z=z}(Y | X=x) = \sum_u E_{Z=z}(Y | U=u,X=x)P_{Z=z}(U=u).
2. Die /Z/ *-bedingte kausale Regression* /E_{Z=z}(Y | X)/ ist kausal erwartungstreu, wenn für alle /Z=z/

   /E(Y | Z=z, X=x)/ = CUE_{Z=z}(Y | X=x).

Es ist beweisbar, dass /E_{Z=z}(Y | X)/ kausal erwartungstreu ist, wenn mindestens eine folgender Bedingungen erfüllt ist:
1. Die Überlebenswahrscheinlichkeit /E(Y | X, U, Z)/, bedingt auf Person /U/ mit Testung /X/ und Kovariaten /Z/, fast sicher (d.h. für alle Kovariaten /Z=z/ mit /P(Z=z)>0/) gleich der Überlebenswahrscheinlichkeit /E(Y | X, Z)/, bedingt auf Testung /X/ und Kovariaten /Z/ ist.

   Dies ist *erfüllt, wenn* /Z/ *all jene Kovariaten umfasst, welche Genesungs-/Sterbewahrscheinlichkeit einer Person beeinflussen.*

   Daher ist eine umfangreiche Erfassung und Veröffentlichung aller Risiko und Protektivfaktoren der Erkrankten notwendig.

2. Positive Testung /X/ und Auswahlwahrscheinlichkeit /U/ stochastisch unabhängig gegeben /Z/ sind. 

   Das Ziel der selektiven Testung durch Kontaktnachverfolgung ist, die Infizierten mit größerer wahrscheinlicher zu testen als die wahrscheinlich nicht Infizierten.  Wenn dieses Ziel erreicht wird, ist diese Bedingung *nicht erfüllt*.

3. Personen-Infektions-Homogenität /E(Y | X,U)/ = E(Y | X) gegeben ist.

   Dies ist *nicht erfüllt*, da offenbar nicht alle test-positiven Personen die gleichen Wahrscheinlichkeiten zu genesen und zu versterben haben.
Nur die erste dieser Bedingungen ist erfüllbar, wenn aufgrund der Testkapazitäten nicht randomisiert getestet wird (2.).
Daher ist es nötig, umfangreiche Patientendaten zur Verfügung zu stellen.

Auf Basis einer repräsentativen Erhebung von Antikörpern scheint Bedingung 2. erfüllt, und eine Einschränkung der Personendaten auf bestimmte Fragestellungen wie Alter, Geschlecht, bestimmte Vorerkrankungen ist hinreichend.
Jedoch selbst in diesem Fall ist es vorteilhaft, möglichst umfangreiche Patientendaten zu veröffentlichen, um Kovariaten zu identifizieren, die einen Einfluss auf den Verlauf der Erkrankung haben, an die aber a-priori niemand gedacht hat.

Steyer, R., Nachtigall, C., Wüthrich-Martone, O., & Kraus, K. (2002). Causal regression models III: Covariates, conditional, and unconditional average causal effects. Methods of Psychological Research Online, 7(1), 41–68.


**** Durchschnittliche kausale Effekte
Wenn die /Z */-bedingte kausale Regression* /E_{Z=z}(Y | X)/ kausal erwartungstreu ist, und die Verteilung der Kovariaten in der Gesamtbevölkerung bekannt ist,  /P'(Z=z)/ ist es möglich, die durchschnittlichen kausalen Effekte in der Gesamtbevölkerung zu berechnen (/P'(Z)/ kann von der Verteilung /P(Z)/ in der getesteten Stichprobe abweichen! Dies ist insbesondere der Fall, wenn nur in symptomatische Patienten in Krankenhäusern getestet werden.).

Die zu erwartende durchschnittliche Mortalitätsrate von Covid19 in der Gesamtbevölkerung entspricht dem durchschnittlichen kausalen Effekt /ACE(Y | X) = \sum_{z \in Z(\Omega)} P'(Z=z) ACE_{Z=z}(Y | X)/.

Es ist beweisbar, dass Marginalisierung über /P'(Z=z)/ eine erwartungstreue Schätzung des durchschnittlichen kausalen Effekts ergibt, wenn die Bedingung erfüllt ist, dass /E_{Z=z}(Y | X)/ kausal erwartungstreu ist für alle /z \in Z(\Omega)/.





*** Anmerkungen zur Erweiterung des Zufallsexperiments:
- /X/: Berücksichtigung verschiedener Tests
- Berücksichtigungen der Zeitpunkte von Testungen, ggf. des Krankheitsverlaufs. 
- /Y/: Vielleicht mit Zeitintervall der Genesung 2 Wochen, vielleicht mehrwertig: genesen, hospitalisiert, verstorben.

*** Statistische Modellierung
Kausale Inferenzstatistik selbst ist kein statistisches Modell!
Vielmehr formuliert kausale Inferenzstatistik die abstrakte wahrscheinlichkeitstheoretische Frage, wie kausale Effekte allgemein definiert sind, auch für nicht-randomisierte kontrollierte Studien.
Statistische Modelle werden in einem zweiten Schritt verwendet um die Wahrscheinlichkeiten an Covid-19 zu versterben, bedingt auf Kovariaten und Teststatus in Regressionen zu schätzen.
In diesem zweiten Schritt haben Forscher statistische Modelle zu testen und kritisch auszuwählen, um zu erwartungstreuen Vorhersagen und Abschätzungen ihrer Zuverlässigkeit zu gelangen.

Logistische Regressionen
1. Modelle logit /P(Y=0 | Z_{i}, X) = \alpha_{0} + \alpha_{1} X + \beta Z_{i} + \gamma X Z_{i}/ für alle Kovariaten /Z_{i}/.
2. Haupteffekte und Interaktionseffekte mit /X/: logit /P(Y=0 | Z, X) = \alpha_{0} + \alpha_{1} X + \sum_{i} \beta_{i} Z_{i}  + \sum_{i} \gamma_{i} X Z_{i}/.
3. Komplexere Modelle zur Abschätzung sind denkbar und wünschenswert.  Ich schlage vor, dass diese Daten anonymisiert öffentlich gemacht werden sollten, um einen freien Wettbewerb für die Vorhersage der Mortalität aus den Kovariaten einzuladen.
4. Bei den voraussichtlich großen Fallzahlen ist ggf. eine nonparametrische und modellfreie Vorhersage möglich.

*** Empfehlungen zur aktuellen Datenveröffentlichung
** Wann hilft und wann schadet Intubation als medizinische Maßnahme?  
Diese Frage beginnt erneut formalen Begriffsklärung durch das Zufallsexperiment.
- Zur Testung wird eine SARS-COV2 positive Person /U=u/ in Intensivpflege ausgewählt
- Die Sauerstoffsättigung wird erhoben, /O=o/
- Kovariaten werden erhoben /Z=z/ (Alter, Geschlecht und Vorerkrankungen etc..)
- Wird die Person intubiert (/X=1/) oder wird sie nicht intubiert (/X=0/)
- Verstirbt (/Y=0/) oder heilt (/Y=1/) die Person?

Der bedingte Kausale Effekt der Intubation auf die Genesungswahrscheinlichkeit für Patienten mit /Z=z, O=o/ ist
ACE_{Z=z,O=o}(Y | X) = /P(Y=1 | X=1, Z=z, O=o)-P(Y=1 | X=0, Z=z, O=o)/.


* Benötigte Daten
# <<daten>>
Optimalerweise würden für die Berechnungen folgende anonymisierten Daten zu jedem getesteten Mitbürger verwendet:
- Testdatum Test-Art und Testergebnis
- Vorerkrankungen
- Hospitalisierungsdatum, falls hospitalisiert
- Entlassungsdatum, falls entlassen
- Versterbedatum, falls verstorben
- Obduktionsdaten, falls verfügbar
- Alter, Geschlecht, wenn möglich Lebensumstände (Rauchen, Luftqualität, Stadt, Land, Ernährungsgewohnheiten, etc)
Zur Bestimmung der kausalen Effekte medizinischer Maßnahmen werden zudem benötigt:
- durchgeführte medizinische Maßnahmen (Intubation, Medikamente)

Voraussichtlich sind manche dieser Daten nicht für alle getesteten Personen verfügbar.
In diesem Fall kann mit geeigneten Verteilungsannahmen die Datenlücke ausgeglichen werden (siehe unten).

* Falls Daten fehlen
Zur statistischen Schätzung dieser Größen sind von den Gesundheitsbehörden folgende Daten erfolderlich:
- Anonymisierte Daten aller getesteten Personen (Testergebnis /X=x/ und Kovariaten /Z=z/).
- Verteilung /P(Z=z)/ in der Population.
- Genesen/Versterben /Y=y/.

Falls die Vorerkrankungen nicht Test-negativer Personen nicht verfügbar sind, ist ggf. eine akzeptable Annahme, dass die Vorerkrankungen der Getesteten ebenso verteilt sind wie in der Gesamtpopulation, bedingt auf das Alter.

Da Sterbedaten der negativ getesteten nicht verfügbar sein dürften, könnte ihre Sterberate /P(Y=0 | Z=z,X=0)/ anhand publizierter Mortalitäten der Vorerkrankungen und des Alters pro Jahr abgeschätzt werden.
Selbst wenn diese Sterberaten verfügbar wäre, ist zu klären, ob es nicht aussagekräftiger ist, die Sterberate innerhalb eines Jahres zugrundezulegen.
