Mit wissenschaftlichen Kollegen und Freunden habe ich in den letzten Woche Möglichkeiten der kausalen Inferenzstatistik zur Erforschung von Sars-Cov2/Covid-19 diskutiert und Artikel und Daten recherchiert.
Leider scheint uns eine statistische Untersuchung kausaler Effekte im Zusammenhang mit Sars-Cov2 vor allem erschwert durch den Mangel an systematisch erfassten Einzelfalldaten mit hinreichenden Kovariaten.

Um Teil der Lösung zu sein habe ich eine Internetseite entworfen, welche das Problem darstellt und die dezentrale Sammlung von freiwilligen Erkrankungs-Datenspenden ermöglicht: https://gkappler.github.io/CausalCovid-19/.

Das Projekt wurde im Geiste der Creative Commons und der transparenten Forschung in einer offenen Gesellschaft initiiert und entworfen.

Ich lade ein, Mängel zu finden -- und freue mich besonders über Mitarbeit per pull-request!

Offene Fragen:
- Datensätze können derzeit nicht mehr verändert werden.



** Open-Source und Creative Commons
Wir unterstützen mit Creative Commons den [Open COVID Pledge](https://opencovidpledge.org/) (
[Creative Commons’ Response to COVID-19](https://creativecommons.org/creative-commons-response-to-covid-19/)).
Sie können sogar eine abgeleitete Version auf Ihrer Internetseite veröffentlichen und so die Datensammlung unterstützen.

Diese Seite nutzt folgende quelloffene Software:
- (https://jekyllrb.com/) Jekyll für das Schreiben und Generieren der Internetseite.
- (https://git-scm.com/) zur Versionierung und Organisation der Daten und Diskussion. 
- (https://staticman.net/) wird zur Erfassung von Kommentaren und Daten genutzt. 

GitHub pages erzeugt aus dem Git Projekt die [[https://gkappler.github.io/CausalCovid-19][statische Website]].


Führen Sie Security-Audits durch?
- Bitte begutachten Sie die Software, und helfen Sie mit Lösungsvorschlägen bei Mängeln!
- Wie kann unser Vorschlag verbessert werden, um alle datenschutzrechtlichen Vorgaben zu erfüllen und Bedenken zu berücksichtigen?
- Könnte durch Recaptcha und verwendete google APIs bei der Datenübertragung deanonymisiert werden?
