Liebe Mitbürger, liebe wissenschaftlichen Kollegen,

Die Corona-Krise bestimmt derzeit maßgeblich unser Leben und unsere Überlegungen.
Extreme Vorsichtsmaßnahmen wurden und werden getroffen.
Täglich ändert sich der Wissensstand und der Stand unserer Überlegungen und Einschätzungen.
Die Ereignisse überstürzen sich und das erschwert sorgfältige randomisierte Studien, um Mortalität und geeignete medizinische Interventionen kontrolliert zu untersuchen.
Wir sind also bisher vor allem auf Beobachtungsdaten beschränkt, und es ist von höchster Wichtigkeit, diese Beobachtungen systematisch zu erfassen und richtig zu beurteilen.

Die Kausalitätstheorie kann kausale Effekte auch bei Beobachtungsstudien untersuchen, wenn bestimmte Bedingungen erfüllt sind.
Beobachtungsstudien sind Datenerhebungen ohne experimentelle Kontrolle, beispielsweise in der gegenwärtigen Corona-Krise, und im Unterschied zu randomisierten Doppel-Blind-Versuchsreihen, wie sie beispielsweise für pharmazeutische Zulassungsverfahren benötigt werden.
Experimente sind der goldene Standard zur Untersuchung von Wirkungen und Nebenwirkungen. 
Doch leider sind sie nicht immer möglich, wie uns diese Pandemie sehr deutlich vor Augen führt.

Ich und meine Kollegen forschten in diesem Bereich und sind der Überzeugung, dass in der heutigen Situation kausale Inferenzstatistik helfen kann, entscheidende aber noch immer offenstehende Fragen für die Allgemeinheit, Politiker und Wissenschaftler zu klären.


** Bitte um kritische Prüfung, Verbesserung und Mitarbeit
Da die Zeit drängt, veröffentliche ich diesen Entwurf mit Vorschlägen zur Datenerhebung, -veröffentlichung und auswertung hier auf GitHub als "lebendes" Dokument.
Auf diese Weise ist es möglich, sehr schnell und öffentlich 
- gemeinsam diese Pläne zu diskutieren und auszuarbeiten
- Daten zusammenzustellen
- statistische Modelle zu veröffentlichen und zu begutachten.

Bitte:
# - Veröffentlichen und teilen Sie den Link zu diesem Dokument (und seinem GitHub repository), um zu helfen, die offenen Fragen in der Corona-Krise mittels statistische Ursachenforschung zu klären und das Wissen um diese Möglichkeiten zu verbreiten.
# - Schreiben Sie ein Unterstützungsschreiben für die Erhebung und Veröffentlichung der [[Daten][Benötigten Daten]].
# - Stellen Sie [[Daten][benötigten Daten]] zusammen.
- [[https://github.com/gkappler/CausalCovid-19/issues][Stellen Sie kritische Fragen zu den Argumenten und Überlegungen in diesem Dokument -- auch als Laie.]]
- Arbeiten Sie an dem Dokument mit, wenn Sie sich dazu in der Lage sehen (Fork rechts oben, bearbeiten und pull request).
- Schlagen Sie Korrekturen vor, wenn Sie Fehler in den Überlegungen dieses Dokuments sehen.
- Tragen Sie statistische Regressionsmodelle bei, die der Kausalschätzung zugrundegelegt werden können.


* Wie gefährlich ist Covid19? Welche Behandlungen wirken? 
Derzeit wird viel diskutiert, ob Menschen "an" oder "mit" Corona versterben.
Die Frage ist, ob Corona *ursächlich* war für das Versterben einer Person, und wie gefährlich Covid-19 im Vergleich zu beispielsweise Influenza ist.
Obwohl diese Frage alle getroffenen Maßnahmen betrifft, ist sie anhand der veröffentlichten Zahlen leider nicht zu beantworten.
Repräsentative Antikörpertests können diese Frage klären und auch Obduktionen tragen durch das Expertengutachten wertvolle Informationen bei.

Die Ärzte in den Intensivstationen müssen täglich Behandlungsentscheidungen treffen.
Kürzlich traten einige Ärzte in Europa und den USA an die Öffentlichkeit, und berichteten Ihre Erfahrungen mit dem Intubieren bei Covid-19 Erkrankten Patienten:
Sie äußerten sich sehr überrascht, dass selbst bei so niedriger Sauerstoffsättigung von ca. 50% viele Ihrer Patienten ohne Intubation die Krankheit überstehen, jedoch die intubierten Patienten zumeist versterben
(https://www.nytimes.com/2020/04/14/nyregion/new-york-coronavirus.html, https://www.youtube.com/watch?v=bp5RMutCNoI).
Derlei Erfahrungen sind anekdotisch und nicht wissenschaftlich.
Dennoch ist es wichtig und richtig, dass Ärzte sich über derlei Erfahrungen anektotisch austauschen:
sie sollen effiziente Behandlungsmethoden finden um Patienten in Intensivstationen bestmöglich zu helfen und sie nicht in bester Absicht mit Behandlungen totzubehandeln, die zwar sonst am besten sind, aber vielleicht bei dieser neuen Erkrankung schädlich.
Ärzte lernen von den Beobachtungen während ihrer Arbeit und durch Austausch und - leider - durch Versuch, Irrtum und Erfolg.
Wissenschaftliche, randomisierte Studien zum Behandlungserfolg von Interventionen gibt es noch nicht.

Es gibt jedoch statistische Verfahren der kausalen Inferenzstatistik, um *ohne* randomisierte Studien zu schätzen, welche medizinischen Maßnahmen Heilung ursächlich begünstigen bzw. negativ beeinflussen:
Die Theorie kausaler Effekte von R. Steyer bzw. propensity score matching nach Rubin.
Vereinfacht gesagt systematisieren diese Verfahren die Analyse anekdotischer Erfahrungen und korrigieren mathematisch die Verzerrungen, welche bei nicht-randomisierten Beobachtungen unvermeidlich sind.
Diese Verfahren ermöglichen auf Basis hinreichender Daten 
1. die Wirksamkeit medizinischer Maßnahmen durch systematische Beobachtung und Erfassung zu bestimmen
3. eine dringend benötigte Schätzung der durchschnittliche Mortalität von Covid19 in der Gesamtbevölkerung zu berechnen,
4. das bedingte Risiko im Falle einer Infektion zu versterben verlässlich zu quantifizieren, für Personen eines bestimmten Alters, Geschlechts und auch für bestimmten Vorerkrankungen.
5. Die Folgen evidenzbasierter Pläne zur Herdenimmunisierung abzuschätzen, d.h. welche 60%-70% der Bevölkerung mit dem geringsten Risiko erkranken könnten, und wie groß das Risiko dieser Personengruppen wäre, an der Erkrankung zu versterben.
6. Diese geschätzten Folgen einer kontrollierten Herdenimmunisieren können dann Annahmen des Risikos von Impfnebenwirkungen gegenübergestellt werden.
Diese Fragen sind in der gegenwärtigen Situation von höchster Dringlichkeit, um Ärzte im Krankenhaus, besorgte Bürger sowie Politiker bei der Entscheidung von Maßnahmen zu beraten.
Mit epidemiologischen Modellrechnungen lassen sich leider diese kausalen Fragen grundsätzlich nicht beantworten.
Vielmehr werden dort informierte, jedoch letztlich hypothetische Annahmen verwendet um Modell-Vorhersagen zu Treffen.


Die Kausalitätstheorie wurde für Umstände wie die Corona-Pandemie entwickelt um kausale Effekte in Beobachtungsstudien zu schätzen, d.h. wenn es nicht möglich ist, eine Kontroll- und Experimentalgruppe zu bilden.
Zur Schätzung von kausalen Inferenz-Modellen wäre es erforderlich, in Krankenhäusern und Gesundheitsämtern vorliegende Daten jedes Einzelfalls in großem Umfang zu erheben und anonymisiert zur Verfügung zu stellen.


Daten auf Ebene von Einzelfällen sind also dringend erforderlich zur bestmöglichen Erforschung der Gefährlichkeit der Erkrankung und der Wirksamkeit von medizinischen Maßnahmen.
Sie fehlen aber.
Leider werden derzeit fast ausschließlich zusammengefasste Fallzahlen, mit unterschiedlicher Aufschlüsselung nach Land, Geschlecht, und Alter veröffentlicht.
Auf Basis dieser Fallzahlen, d.h. ohne Daten auf Ebene von Einzelfällen lassen sich jedoch obige drängendsten Fragen nicht beantworten.
Stand [2020-04-19 So] hat meines Wissens nur China Daten infizierter Personen zur Verfügung gestellt, auf deren Basis bereits wichtige und hochrangig publizierte Studien ermöglicht wurden.
- https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30243-7/fulltext 
- https://www.bmj.com/content/369/bmj.m1327

Wir regen an, die zentrale Sammlung und Veröffentlichung dieser Daten sofort zu veranlassen.
Offensichtlich sind diese Gesundheitsdaten rechtlich besonders geschützt.
Unsere westliche Demokratien sind bereit, die Notwendigkeit von Chinas autoritären Maßnahmen der Ausgangssperre und Ortsdatenüberwachung zur Eindämmung der Erkrankung zu erwägen und zu adaptieren.
Westliche Demokratien sollten diskutieren, ob es nicht ein geringerer Eingriff in das soziale Gefüge freier Gesellschaften wäre, zuerst den Schutz persönlicher Daten für Erkrankte und Verstorbene im Seuchenfall einzuschränken.
Es ist an der Vielzahl an Studien zu den Chinesischen Einzelfalldaten deutlich abzulesen, dass diese Aufhebung des Schutzes von Krankheitsdaten Wissenschaftlern ermöglich, wertvolle und praktische Erkenntnisse über die Covid-19 Erkrankheit zu erforschen.


Während für die Erforschung der durch den Virus verursachten Erkrankung Covid-19 augenfällig offene Daten fehlen, ist bei der Erforschung des SARS-Cov2 Genoms eine vorbildlich offene Forschungssituation zu beobachten:
die nötigen Daten für die wissenschaftliche Gemeinschaft sind offen verfügbar und ermöglichen eine nie dagewesene Beschleunigung der Erforschung (siehe European Commission https://horizon-magazine.eu/article/covid-19-how-unprecedented-data-sharing-has-led-faster-ever-outbreak-research.html).

Zumindest die freiwillige Freigabe der Daten durch Patienteneinverständnis sollte ab sofort eingeholt werden, und eine entsprechende Dateninfrastruktur des Europäischen Center of Desease Control vorbereitet werden.
Für bereits verstorbene Patienten sind wir der Überzeugung, dass eine Rechtsgüterabwägung die Nutzung dieser anonymisierten Daten ebenso oder leichter zulässt als die Erfassung von Bewegungsdaten der Bevölkerung.
Wir wollen eine öffentliche Diskussion über den Umgang mit Daten zur Wissenschaftlichen Untersuchung in dieser Corona-Krise anregen.

Katastrophen sind plötzlich und unübersichtlich.
Um in zukünftigen Katastrophen angemessen reagieren zu können, scheint es uns ganz besonders wichtig, aus dieser Katastrophe zu lernen, wie schneller ein gutes Bild der Lage erlangt werden kann.
Daher regen wir an, die Veröffentlichung anonymisierter Daten zu den Verstorbenen bei zukünftigen Pandemien als gesetzlichen Automatismus im Seuchenschutzgesetz zu verankern.
Nur auf diese Weise ist gewährleistet, dass die internationale Forschergemeinschaft mit im Seuchenfall gebotener Geschwindigkeit und Aktualität die Gefährlichkeit der Erkrankung erforschen und evidenzbasierte Hinweise für praktische Ärzte geben kann, welche der getroffenen medizinischen Maßnahmen wirken und zu warnen, welche Maßnahmen schaden.

** Übersterblichkeit, Kausalitätstheorie und Zufallsexperiment
Die Kausalitätstheorie nach Rolf Steyer beginnt mit einer formalen Begriffsklärung durch das Zufallsexperiment.
Zur verständlichen Beschreibung der Theorie in Bezug auf Corona die reduzierteste Fassung ohne Berücksichtigung der Zeitpunkte oder des Krankheitsverlaufs:
- Zur Testung wird eine Person /U=u/ aus der Population ausgewählt (nicht randomisiert, sondern gemäß Testprotokoll).
- Die Person ist mit Covid-19 infiziert, /X'/ (wird nicht direkt beobachtet, sondern anhand Test erhoben). 
- Das Testergebnis der Person wird erhoben, /X=x/. 
- Kovariaten werden erhoben /Z=z/ (Alter, Geschlecht und Vorerkrankungen etc..)
- Erkrankt die Person (/S=1/) oder bleibt sie asymptomatisch (/S=0/)
- Verstirbt (/Y=0/) oder heilt (/Y=1/) die Person?

Wahrscheinlichkeitstheoretisch sind dies Zufallsvariablen
- /U : \Omega \rightarrow/ Population
- /X' : \Omega \rightarrow {0,1}/
- /X : \Omega \rightarrow {0,1}/
- /Z : \Omega \rightarrow Z_{1} \times...\times Z_{n}/
- /S : \Omega \rightarrow {0,1}/
- /Y : \Omega \rightarrow {0,1}/

*** Infektion und Test
Die Erkrankung an Covid-19 kann nur indirekt durch Tests erhoben werden.
Tests sind niemals absolut zuverlässig sondern durch Sensititivtät und Spezifizität gekennzeichnet, in bedingten Wahrscheinlichkeiten ausgedrückt[fn::https://www.centerforhealthsecurity.org/resources/COVID-19/serology/Serology-based-tests-for-COVID-19.html]:
- Sensitivität: /1-P(X=1 | X=0)/
- Spezifizität: /1-P(X=0 | X=1)/


*** Was ist die Übersterblichkeit durch Corona in der erhobenen Stichprobe?
In den definierten Begriffen dieses Zufallsexperiments wären die Anteile (Wahrscheinlichkeiten) der versterbenden Personen in der Testpopulation
- mit Corona-Infektion: /P(Y=0 | X=0)/
- ohne Corona-Infektion: /P(Y=0 | X=1)/.

Der durchschnittliche kausale Effekt einer Covid-19 Erkrankung auf die Sterblichkeit innerhalb der getesteten Stichprobe entspricht der Differenz dieser Wahrscheinlichkeiten /P(Y=0 | X=1)-P(Y=0 | X=0)/ und kann als durch *Covid-19 bedingte Übersterblichkeit innerhalb der Stichprobe* interpretiert werden.
Hier stellen sich grundsätzliche Probleme:
- Die Stichprobe ist nicht repräsentativ für die Gesamtbevölkerung.
- Die Wahrscheinlichkeit mit negativem Test zu versterben ist anhand der erfassten Testdaten nicht möglich.
  Diese Wahrscheinlichkeit könnte jedoch auf Basis veröffentlichter Sterberaten der Vorjahre abgeschätzt werden.
- Die Zufallsvariablen der Genesung /Y/ kann erst nach dem Ende der Erkrankung erhoben werden. Wahrscheinlichkeit mit positivem Test zu versterben ist nur für den Anteil der positiv getesteten zu ermitteln, die bereits genesen oder verstorben sind.

Für Personen, die durch Geschlecht, Alter und Vorerkrankungen /Z=z/ charakterisiert sind, und 
- positiv auf Covid19 getestet wurden, ist das bedingte Sterberisiko /P(Y=0 | Z=z,X=1)/,
- negativ auf Covid19 getestet wurden, ist das bedingte Sterberisiko /P(Y=0 | Z=z,X=0)/,
Der /Z/-bedingte kausale Effekt von Covid19 auf die Sterberate ist definiert als die Differenz dieser bedingten Wahrscheinlichkeiten /E_{Z=z}(Y|X) = P(Y=0 | Z=z,X=1) - P(Y=0 | Z=z,X=0)/.
Dieser bedingte Effekt /E_{Z=z}(Y|X)/ is spezifisch für Personen, die durch Kovariaten /Z=z/ (Alter, Vorerkrankungen, etc.) charakterisiert sind, und für diese Gruppe definiert als der Mehr-Anteil der versterbenden Personen, die Covid-19 positiv getestet wurden, über die zu erwartende Sterblichkeitsrate von Covid-19 negativ getesteten Personen hinaus.
*Es handelt sich also um die Covid-19 bedingte Übersterblichkeit von Personen mit Kovariaten Z=z.* 

*** Verallgmeinerung auf die Bevölkerung
**** Kausale Erwartungstreue 
Definitionen
1. Der *(/Z=z/)-bedingte kausal erwartungstreue Erwartungswert von /Y/ gegeben /X=x*/ ist definiert als

   CUE_{Z=z}(Y|X=x) = \sum_u E_{Z=z}(Y|U=u,X=x)P_{Z=z}(U=u).
2. Die /Z/-bedingte kausale Regression /E_{Z=z}(Y|X)/ ist kausal erwartungstreu, wenn

   /E_{Z=z}(Y|X=x)/ = CUE_{Z=z}(Y|X=x).

Es ist beweisbar, dass /E_{Z=z}(Y|X)/ kausal erwartungstreu ist, wenn die Bedingung erfüllt ist, dass /X/ und /U/ stochastisch unabhängig gegeben /Z/ sind.
Dies ist erfüllt, wenn die Wahrscheinlichkeit ein positives Testergebnis zu erhalten unabhängig ist von der Wahrscheinlichkeit dass eine Person getestet wird, bedingt auf die Kovariate $Z$.

*Ist das sicher der Fall?*

Steyer, R., Nachtigall, C., Wüthrich-Martone, O., & Kraus, K. (2002). Causal regression models III: Covariates, conditional, and unconditional average causal effects. Methods of Psychological Research Online, 7(1), 41–68.


**** Durchschnittliche kausale Effekte
Sei /P'(Z=z)/ die Verteilung der Kovariaten in der Gesamtbevölkerung, welche von der Verteilung /P(Z)/ in der getesteten Stichprobe möglicherweise abweicht.
Die zu erwartende durchschnittliche Mortalitätsrate von Covid19 in der Gesamtbevölkerung entspricht dem durchschnittlichen kausalen Effekt /\eta' = \sum_{z \in Z(\Omega)} P'(Z=z) \eta_{Z=z}/.

Es ist beweisbar, dass Marginalisierung über /P'(Z=z)/ eine erwartungstreue Schätzung des durchschnittlichen kausalen Effekts ergibt, wenn die Bedingung erfüllt ist, dass /E_{Z=z}(Y|X)/ kausal erwartungstreu ist für alle /z \in Z(\Omega)/.





*** Anmerkungen zur Erweiterung des Zufallsexperiments:
- /X/: Berücksichtigung verschiedener Tests
- Berücksichtigungen der Zeitpunkte von Testungen, ggf. des Krankheitsverlaufs. 
- /Y/: Vielleicht mit Zeitintervall der Genesung 2 Wochen, vielleicht mehrwertig: genesen, hospitalisiert, verstorben.

*** Statistische Modellierung
Kausale Inferenzstatistik selbst ist kein statistisches Modell!
Vielmehr formuliert kausale Inferenzstatistik die abstrakte wahrscheinlichkeitstheoretische Frage, wie kausale Effekte allgemein definiert sind, auch für nicht-randomisierte kontrollierte Studien.
Statistische Modelle werden in einem zweiten Schritt verwendet um die Wahrscheinlichkeiten an Covid-19 zu versterben, bedingt auf Kovariaten und Teststatus in Regressionen zu schätzen.
In diesem zweiten Schritt haben Forscher statistische Modelle zu testen und kritisch auszuwählen, um zu erwartungstreuen Vorhersagen und Abschätzungen ihrer Zuverlässigkeit zu gelangen.

Logistische Regressionen
1. Modelle logit /P(Y=0 | Z_{i}, X) = \alpha_{0} + \alpha_{1} X + \beta Z_{i} + \gamma X Z_{i}/ für alle Kovariaten /Z_{i}/.
2. Haupteffekte und Interaktionseffekte mit /X/: logit /P(Y=0 | Z, X) = \alpha_{0} + \alpha_{1} X + \sum_{i} \beta_{i} Z_{i}  + \sum_{i} \gamma_{i} X Z_{i}/.
3. Komplexere Modelle zur Abschätzung sind denkbar und wünschenswert.  Ich schlage vor, dass diese Daten anonymisiert öffentlich gemacht werden sollten, um einen freien Wettbewerb für die Vorhersage der Mortalität aus den Kovariaten einzuladen.
4. Bei den voraussichtlich großen Fallzahlen ist ggf. eine nonparametrische und modellfreie Vorhersage möglich.

*** Empfehlungen zur aktuellen Datenveröffentlichung
* Benötigte Daten
# <<daten>>
Optimalerweise würden für die Berechnungen folgende anonymisierten Daten zu jedem getesteten Mitbürger verwendet:
- Testdatum Test-Art und Testergebnis
- Vorerkrankungen
- Hospitalisierungsdatum, falls hospitalisiert
- Entlassungsdatum, falls entlassen
- Versterbedatum, falls verstorben
- Obduktionsdaten, falls verfügbar
- Alter, Geschlecht, wenn möglich Lebensumstände (Rauchen, Luftqualität, Stadt, Land, Ernährungsgewohnheiten, etc)
Zur Bestimmung der kausalen Effekte medizinischer Maßnahmen werden zudem benötigt:
- durchgeführte medizinische Maßnahmen (Intubation, Medikamente)

Voraussichtlich sind manche dieser Daten nicht für alle getesteten Personen verfügbar.
In diesem Fall kann mit geeigneten Verteilungsannahmen die Datenlücke ausgeglichen werden (siehe unten).

* Falls Daten fehlen
Zur statistischen Schätzung dieser Größen sind von den Gesundheitsbehörden folgende Daten erfolderlich:
- Anonymisierte Daten aller getesteten Personen (Testergebnis /X=x/ und Kovariaten /Z=z/).
- Verteilung /P(Z=z)/ in der Population.
- Genesen/Versterben /Y=y/.

Falls die Vorerkrankungen nicht Test-negativer Personen nicht verfügbar sind, ist ggf. eine akzeptable Annahme, dass die Vorerkrankungen der Getesteten ebenso verteilt sind wie in der Gesamtpopulation, bedingt auf das Alter.

Da Sterbedaten der negativ getesteten nicht verfügbar sein dürften, könnte ihre Sterberate /P(Y=0 | Z=z,X=0)/ anhand publizierter Mortalitäten der Vorerkrankungen und des Alters pro Jahr abgeschätzt werden.
Selbst wenn diese Sterberaten verfügbar wäre, ist zu klären, ob es nicht aussagekräftiger ist, die Sterberate innerhalb eines Jahres zugrundezulegen.
